### ISSUE TITLE
Validation tool not working at 1.1.14

### ISSUE THREAD

**Issue by llamentowski** [ngageoint/sarpy_apps#42]
Steps taken:
Installed sarpy from latest master 
`
(sarpy-test) llamentowski@DESKTOP-8575LM6:~/code/python/sarpy_apps (master)$ conda list | grep sarpy
packages in environment at /home/llamentowski/anaconda3/envs/sarpy-test:
sarpy                     1.2.12                   pypi_0    pypi
`
Installed sarpy-apps from latest master:
`(sarpy-test) llamentowski@DESKTOP-8575LM6:~/code/python/sarpy_apps (master)$ python setup.py install`
(...)
`Using /home/llamentowski/anaconda3/envs/sarpy-test/lib/python3.8/site-packages
Finished processing dependencies for sarpy-apps==1.1.14
`

Trying to run validation tool errors with:
`(sarpy-test) llamentowski@DESKTOP-8575LM6:~/code/python/sarpy_apps (master)$ python sarpy_apps/apps/validation_tool.py 
Traceback (most recent call last):
  File "sarpy_apps/apps/validation_tool.py", line 26, in <module>
    from sarpy_apps.apps.aperture_tool import RegionSelection
ImportError: cannot import name 'RegionSelection' from 'sarpy_apps.apps.aperture_tool' (/home/llamentowski/anaconda3/envs/sarpy-test/lib/python3.8/site-packages/sarpy_apps-1.1.14-py3.8.egg/sarpy_apps/apps/aperture_tool/__init__.py)
`
Though:
`(sarpy-test) llamentowski@DESKTOP-8575LM6:~/code/python/sarpy_apps (master)$ cat sarpy_apps/apps/aperture_tool.py | grep RegionSelection`

`class RegionSelection(Frame, WidgetWithMetadata):
    app = RegionSelection(root, reader=reader)
`

**Comment by tommccullough-tenica** [comment]
Hi Leszek, that class definitely exists in the place that it's shown being imported, so something else is going wrong somehow.

One thing that I notice is that you did a direct `python setup.py install` for `sarpy_apps`. Have you ever installed `sarpy_apps` before? I should add some clarifying language to my readmes about installing via setup.py install, because it behaves horribly for packages that are already installed. 

I would delete any mention of sarpy_apps from your environment and  proceed again. Generally, if you intend to fiddle with development, then I recommend adding a .pth file inside you environment - see the docs for .pth description [https://docs.python.org/3.8/library/site.html](https://docs.python.org/3.8/library/site.html)

I don't remember why exactly, but sarpy_apps requires sarpy>=1.2.36, so you see some kind of unfortunate trouble somewhere if you don't update your sarpy. Feel free to email me directly for anything else surrounding this. Thanks! 

-Tom
